# Generated by Django 4.2.4 on 2023-10-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='book',
            name='count_comment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد نظرات'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ایجاد')),
                ('approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='تایید شده')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('rate', models.IntegerField(blank=True, default=5, null=True, verbose_name='امتیاز')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_comment', to='book.book', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
