# Generated by Django 4.2.4 on 2023-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='امتیاز'),
        ),
    ]
